# Schema for the configuration files of the youtrack_logger module.

youtrack_logger.settings:
  type: config_object
  label: 'YouTrack Logger settings'
  mapping:
    summary_format:
      type: string
      label: 'Summary format'
    description_format:
      type: string
      label: 'Description format'
    project:
      type: string
      label: 'Project'
    commands:
      type: string
      label: 'Commands'
    severities:
      type: array
      label: 'Severities'
