youtrack.settings:
  type: config_object
  label: 'YouTrack settings'
  mapping:
    youtrack_url:
      type: string
      label: 'REST API URL'
    youtrack_login:
      type: string
      label: 'Login'
    youtrack_password:
      type: string
      label: 'Password'